feat: add env pull/push commands
Dokploy/cli pull request #3
Opened 2024-11-20 03:16 UTC by kidylee

Add new commands to pull the environment variables from remote to local dotfile and vice versa.

Resolves Dokploy/dokploy#555

2024-12-12 05:06 UTC, kidylee commented
Please have a review, thanks. @Siumauricio

2024-12-21 08:03 UTC, Siumauricio requested changes

2024-12-21 08:03 UTC, Siumauricio commented on src/commands/env/pull.ts
> +        fs.writeFileSync(args.file, env)
```suggestion
        fs.writeFileSync(args.file, env || "")
```

2024-12-21 08:04 UTC, Siumauricio commented
Thanks! @kidylee sorry for the delay

2024-12-21 08:04 UTC, merged